serialization works but still not fast
also iteration 0 converges and then iteration 1 breaks like this

thread 'main' panicked at src/main.rs:174:39:
ndarray: index (995, 0) is out of bounds for array of shape [995, 1]

don't know why it doesn't stop before going too far